const sqlite3 = require('sqlite3');
const path = require('path');
const databasePath = './database/guardian_link.db';

// initialize bcrypt for hashing
const bcrypt = require('bcrypt');
const saltRounds = 10; // salt rounds used for hashing
const defaultPassword = bcrypt.hash('changeme', saltRounds);


// import logger
const logger = require('../backend/app');
logger.info('Attempting to connect to database.');


// Open database, or create new one if doesn't exist
const db = new sqlite3.Database(databasePath, (error) => {
    if (error) {
        logger.error('Error opening database: ', error.message);
    } else {
        logger.info('Database successfully opened');
    }}
);

// serialize tasks to prevent execution ordering issues
db.serialize(() => {
    // Check if the database already contains desired tables, create if not
    db.get(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`, 'users', (error, row) => {
        if (error) {
            logger.error('Error checking table existence: ', error.message);
            return;
        }
        else {
            if (!row) {
                // Users table does not exist
                try {
                    // serialize tasks to prevent execution ordering issues
                    db.serialize(() => {
                        // Create table
                        db.run(`CREATE TABLE IF NOT EXISTS users (
                            userID INTEGER PRIMARY KEY AUTOINCREMENT,
                            accountType TEXT NOT NULL,
                            name TEXT NOT NULL, 
                            username TEXT NOT NULL UNIQUE,
                            email TEXT NOT NULL, 
                            password TEXT NOT NULL,
                            availability INTEGER,
                            backgroundCheck INTEGER,
                            isCurrentlyAvailable INTEGER,
                            linkedin TEXT,
                            concerns TEXT,
                            missionStatement TEXT)`);

                        // Create default credentials for admin role
                        db.run("INSERT INTO users (accountType, name, username, email, password) " + 
                            "VALUES('super','GL_Admin','GL_Admin','admin@guardianlink.com', '" + defaultPassword + "')");
                    });                                            
                    
                    logger.info('users table created successfully.'); 

                } catch (error) {
                    logger.error('Error creating users table: ', error.message);
                }
            }
        }
    });

    // // create messages table if doesn't exist
    // // timestamp is autogenerated by sqlite
    // db.get(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`, 'messages', (error, row) => {
    //     if (error) {
    //         logger.error('Error checking table existence: ', error.message);
    //         return;
    //     }
    //     if (!row) {
    //         try {
    //             db.run(`CREATE TABLE IF NOT EXISTS messages (
    //                 id INTEGER PRIMARY KEY AUTOINCREMENT,
    //                 senderID INTEGER NOT NULL,
    //                 receiverID INTEGER NOT NULL,
    //                 time TEXT DEFAULT strftime('%d-%m-%Y - %H:%M:%S', 'now'),
    //                 message TEXT NOT NULL,
    //                 FOREIGN KEY (senderID) REFERENCES users(userID),
    //                 FOREIGN KEY (receiverID) REFERENCES users(userID))`);
    //             logger.info('messages table created successfully.'); 
    //         } catch (error) {
    //             logger.error('Error creating messages table: ', error.message);
    //         }
    //     }
    // });


});

// close the database
db.close((error) => {
    if (error) {
        logger.error('Error closing database connection:', error.message);
    }
    else {
        logger.info('Database connection closed');
    }
})